[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.module]
source = "lib/json.lua"
name = "eb_latro_json"

[[patches]]
[patches.module]
source = "lib/pollnet.lua"
name = "eb_latro_pollnet"

[[patches]]
[patches.module]
source = "lib/buttplug.lua"
name = "eb_latro_buttplug"

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "function love.update( dt )"
position = "after"
payload = '''
    if pollButtplugMessages then pollButtplugMessages() end
'''
match_indent = true
times = 1
